if(sessionStorage.getItem("bank_admin")!=="1")location.href="index.html";
function render(){const db=loadDB(),q=(document.getElementById("search").value||"").toLowerCase();const users=db.users.filter(u=>u.id.includes(q)||u.name.toLowerCase().includes(q));document.getElementById("totalUsers").textContent=db.users.length;document.getElementById("totalBalance").textContent=money(db.users.reduce((s,u)=>s+Number(u.balance||0),0));document.getElementById("totalTx").textContent=db.users.reduce((s,u)=>s+(u.transactions||[]).length,0);
document.getElementById("users").innerHTML=users.map(u=>`<tr><td><b>${esc(u.id)}</b></td><td>${esc(u.name)}</td><td><b>${money(u.balance)}</b></td><td>${u.status==="active"?'<span class="credit">Hoạt động</span>':'<span class="danger">Đã khóa</span>'}</td><td><div class="actions"><button class="ghost" onclick="adjust('${u.id}')">+/- Số dư</button><button class="ghost" onclick="toggle('${u.id}')">${u.status==="active"?"Khóa":"Mở"}</button><button class="ghost" onclick="editUser('${u.id}')">Sửa</button></div></td></tr>`).join("")||'<tr><td colspan="5">Không có dữ liệu</td></tr>'}
function openCreate(){document.getElementById("modalTitle").textContent="Tạo tài khoản";document.getElementById("userForm").reset();document.getElementById("editId").value="";document.getElementById("newAccount").disabled=false;document.getElementById("modal").classList.remove("hidden")}
function editUser(id){const u=loadDB().users.find(x=>x.id===id);if(!u)return;document.getElementById("modalTitle").textContent="Chỉnh sửa tài khoản";document.getElementById("editId").value=u.id;document.getElementById("name").value=u.name;document.getElementById("newAccount").value=u.id;document.getElementById("newAccount").disabled=true;document.getElementById("newPassword").value=u.password;document.getElementById("newEmail").value=u.email||"";document.getElementById("newPhone").value=u.phone||"";document.getElementById("newBalance").value=u.balance;document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function toggle(id){const db=loadDB(),u=db.users.find(x=>x.id===id);u.status=u.status==="active"?"locked":"active";saveDB(db);render()}
function adjust(id){const db=loadDB(),u=db.users.find(x=>x.id===id);const raw=prompt(`Nhập số tiền muốn cộng/trừ cho ${u.name}. Ví dụ: 500000 hoặc -500000`);if(raw===null)return;const amount=Number(raw);if(!Number.isFinite(amount)||amount===0){alert("Số tiền không hợp lệ.");return}if(u.balance+amount<0){alert("Không thể làm số dư âm.");return}u.balance+=amount;u.transactions=u.transactions||[];u.transactions.push({time:now(),note:"Điều chỉnh bởi Admin",type:amount>0?"credit":"debit",amount:Math.abs(amount),balance:u.balance});saveDB(db);render()}
document.getElementById("userForm").addEventListener("submit",e=>{e.preventDefault();const db=loadDB(),edit=document.getElementById("editId").value,id=document.getElementById("newAccount").value.trim();if(!edit&&db.users.some(u=>u.id===id)){document.getElementById("adminMsg").textContent="Số tài khoản đã tồn tại.";return}
if(edit){const u=db.users.find(x=>x.id===edit);u.name=document.getElementById("name").value.trim();u.password=document.getElementById("newPassword").value;u.email=document.getElementById("newEmail").value.trim();u.phone=document.getElementById("newPhone").value.trim();u.balance=Number(document.getElementById("newBalance").value)||0}else{db.users.push({id,name:document.getElementById("name").value.trim(),password:document.getElementById("newPassword").value,email:document.getElementById("newEmail").value.trim(),phone:document.getElementById("newPhone").value.trim(),balance:Number(document.getElementById("newBalance").value)||0,status:"active",created:new Date().toISOString().slice(0,10),transactions:[]})}
saveDB(db);closeModal();render()});render();